modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="unsend"
version="${version}"
displayName="Unsay"
authors="bielzinrx"
logoFile="icon.png"
description='''
Delete, edit and reply to chat messages. Hold Shift on your message to delete for everyone.
'''

[[dependencies.unsend]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.unsend]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
